started work on sopel frontend for opendere, and some changes to the opendere game logic itself
opendere/opendere pull request #1
Opened 2019-08-24 22:30 UTC by libbies

2019-08-24 22:42 UTC, opendere requested changes
Looks good for the most part. One thing I thought would be cool was to make an abstract `Game`, then `class IrcGame(Game)` could handle all irc logic, and other platforms like discord could easily be extended to.

2019-08-24 22:42 UTC, opendere commented on opendere/game.py
> -        self.users_alive = {username: True for username in usernames}
how do we track dead and alive users?

2019-08-24 22:42 UTC, opendere commented on opendere/game.py
> +    def _get_phase_name(self):
I recommend
```
@property
def phase_name(self):
```

then you can do `self.phase_name`

2019-08-25 00:28 UTC, libbies commented on opendere/game.py
> -        self.users_alive = {username: True for username in usernames}
users_alive = [user for user in self.users if user.alive == True]

2019-08-25 21:47 UTC, opendere commented on opendere/game.py
> +        self.uid = uid
nice, more general

2019-08-25 21:48 UTC, opendere commented on opendere/game.py
> +        # why aren't these weights in roles.py instead? - libbies
I think role selection should be generic. We can have other variants with other roles. I view these as not features of roles, but features of games.

2019-08-25 21:49 UTC, opendere approved these changes

2019-08-25 21:49 UTC, merged

2019-08-25 21:52 UTC, opendere commented on opendere/game.py
> +        role_classes += list(weighted_choices(weighted_good_and_neutral_role_classes, num_users - num_yanderes))
I think we need logic to ensure neutral roles are limited and only appear if there are enough users. IIRC, they only appear with 6 or more players, and there are generally at most 1 neutral per 6 users.

2019-08-26 15:16 UTC, libbies commented on opendere/game.py
> +        role_classes += list(weighted_choices(weighted_good_and_neutral_role_classes, num_users - num_yanderes))
would just increasing the weight of all the good classes work? I was thinking about doubling all of those weights just so that 'spy/dayspy' doesn't have double the likelihood of all the other upgraded classes.