[WIP] implemented voting and tests for voting...
opendere/opendere pull request #8
Opened 2019-09-04 04:40 UTC by libbies

2019-09-04 13:01 UTC, opendere commented on opendere/ability.py
> +    is_exclusively_phase_action = False
`is_exclusively_phase_action` determines whether the action is executed immediately, so maybe this should be `True` so it's added to the `phase_actions`?

2019-09-04 13:01 UTC, opendere commented on opendere/action.py
> +        if self.game.phase_seconds_left <= 0:
Isn't this redundant with https://github.com/opendere/opendere/pull/8/files#diff-9ed88aea4711a1651388f83724ee58f4R34 ? I don't think we should handle determining whether or not we're at the end of a phase here.

Separately, IMO, we should handle someone entering a vote in `VoteToKillAction.__init__`. The init function can
1. create the object
2. count the votes
3. create the messages caused by the vote count
4. trigger a phase end if the vote count calls for it

In general `__init__` can create `Action.messages` and that attribute can be used by `Game` to propagate the messages.

Then `__call__` can actually execute the vote count.

2019-09-04 13:01 UTC, opendere commented on opendere/action.py
> +            # modify the previous vote if one exists
seems better to handle in `__init__`. Then you can just delete the vote if its `user` is the same as the new votes `user`

2019-09-04 13:01 UTC, opendere commented on opendere/action.py
> +                self.game.phase_actions.append(VoteToKillAction(self.game, self.user, self.target_user))
oh I see why you made it an immediate action now, but I think it would be better to make it a phase action and move the logic to `__init__` so we can follow the pattern that other actions follow.

2019-09-04 13:01 UTC, opendere commented on opendere/action.py
> +        # FIXME: need to rewrite this, hide action shouldn't be *deleting* actions
seems like a hack, but maybe we could have a copy of self.game.phase_actions (self.game.unprocessed_phase_actions?) for info roles observation.

2019-09-05 14:57 UTC, opendere commented on opendere/action.py
> +        # TODO: the game should immediately end if all the yanderes are dead
ending the game based on yandere count this shouldn't be handled in `KillAction`

2019-09-05 14:57 UTC, opendere commented on opendere/action.py
> +        if self.game.num_yanderes_alive == 0 or self.game.num_yanderes_alive > self.game.num_players_alive:
I don't think this logic should be part of `KillAction`.

For phase actions, we should let all actions be executed, then evaluate whether the game is over. For instant actions, we can evaluate each time whether the game is over.

2019-09-05 14:57 UTC, opendere commented on opendere/action.py
> +        reply_to = [self.game.channel] \
nit: I recommend just using 
```
if foo:
    bar
else:
    baz
```
much easier to read

2019-09-05 14:57 UTC, opendere commented on opendere/action.py
> +            previous_vote.user, previous_vote.target_user = None, None
I would just delete the `previous_vote` from `phase_actions`

2019-09-05 14:57 UTC, opendere commented on opendere/action.py
> +        # player hasn't voted yet
IMO, cleaner to do
```
if previous_vote:
   prev_vote_name = #prev_vote
   # delete previous vote here
else:
    prev_vote_name = #undecided
vote_message = "player has changed their vote from {} to {}".format(prev_vote_name, rest_of_message)
```

2019-09-05 14:57 UTC, opendere commented on opendere/action.py
> +            if self.target_user == 'undecided':
`self.user` shouldn't be changed here.

2019-09-05 14:57 UTC, opendere commented on opendere/action.py
> +        for target in {action.target_user for action in self.actions_of_my_type if isinstance(action.target_user, opendere.game.User)}:
You can remove the `isinstance` if you delete unused votes mentioned above

2019-09-05 14:57 UTC, opendere commented on opendere/action.py
> +            # should we have the person executing the killaction be a yandere if it's night?
maybe `self.user` should be a list of `self.acting_users`. Some actions require multiple people to execute them.

2019-09-05 14:57 UTC, opendere commented on opendere/action.py
> +                KillAction(self.game, killer if self.game.phase_name == 'night' else None, most_voted_user)
I don't think we need a `KillAction` added to the phase_actions. This code could execute the kill itself.

2019-09-05 14:57 UTC, opendere commented on opendere/game.py
> +            if action.user or action.target_user:
shouldn't the messages created by an action always be added to the `messages` list?

2019-09-05 14:57 UTC, opendere commented on opendere/game.py
> +            # NOTE: I think Ability.name should be changed to ability.commands = {command_name: num_params}
sounds good to me. Although are there any abilities that have multiple commands? If not, it may be smarter to have `command_params = ['commandname', 'param1', ...]`

2019-09-05 14:58 UTC, libbies commented on opendere/action.py
> +        # TODO: the game should immediately end if all the yanderes are dead
where should it go instead? only place I can think of otherwise is tick()

2019-09-06 03:39 UTC, libbies commented on opendere/action.py
> +        # FIXME: need to rewrite this, hide action shouldn't be *deleting* actions
there's a game.completed_actions now...

2019-09-06 03:39 UTC, libbies commented on opendere/action.py
> +        for target in {action.target_user for action in self.actions_of_my_type if isinstance(action.target_user, opendere.game.User)}:
I don't think I can... because 'abstain's are still in the pool

2019-09-06 03:40 UTC, libbies commented on opendere/action.py
> +            # should we have the person executing the killaction be a yandere if it's night?
fuck it, every yandere is now off on a murdering spree :3

2019-09-06 03:40 UTC, libbies commented on opendere/action.py
> +                KillAction(self.game, killer if self.game.phase_name == 'night' else None, most_voted_user)
I disagree, no point in duplicating this code in both places?

2019-09-06 03:43 UTC, opendere commented on opendere/ability.py
> +                game.phase_actions.remove(previous_action)
It's good to have this here :thumbup:

2019-09-06 03:44 UTC, opendere commented on opendere/ability.py
> +        if self.is_exclusively_phase_action or game.phase_name == 'night':
shouldn't this apply to phase actions during the day too?

2019-09-06 03:45 UTC, opendere commented on opendere/ability.py
> +                self.num_uses -= 1
hmm, I wonder if this should be decremented in the `Action.__call__`? Sometimes actions are overridden by future actions (e.g. a vote is replaced by another vote)

2019-09-06 03:48 UTC, opendere commented on opendere/action.py
> +                if (isinstance(action, HideAction) and action.user == self.target_user)
maybe it would be best to implement
`def is_user_protected()` and call that

2019-09-06 04:18 UTC, opendere commented on opendere/action.py
> +                KillAction(self.game, killer if self.game.phase_name == 'night' else None, most_voted_user)
You don't need to duplicate. You just can create and execute the KillAction here without appending it to the phase_actions.

2019-09-06 05:20 UTC, libbies commented on opendere/action.py
> +                KillAction(self.game, killer if self.game.phase_name == 'night' else None, most_voted_user)
oh. since it's already executing in the phase actions. duh. okay I can do that.

2019-09-06 05:20 UTC, libbies commented on opendere/action.py
> +                if (isinstance(action, HideAction) and action.user == self.target_user)
yeah, just wanted to figure out what it would look like. I'll move it.

2019-09-10 02:33 UTC, opendere commented on opendere/ability.py
> +        previous_action = next((act for act in game.phase_actions if isinstance(act, type(self)) and user == act.user), None)
I recommend defining Action.__hash__ and checking if `action_obj in game.phase_actions`

2019-09-10 02:38 UTC, opendere commented on opendere/ability.py
> +            self.num_uses -= 1
I recommend not decrementing `self.num_uses` until the action is applied. One way to do this is for `Action`s to optionally have `parent_ability`. Changing the state here then reversing, especially when the action isn't even guaranteed to be `__call__`ed will result in a mess.

2019-09-10 02:41 UTC, opendere commented on opendere/action.py
> +            self.previous_vote = Action(None, None, 'undecided')
since you changed to `previous_target`, you can get rid of this and just have `previous_target` default to `undecided`.

2019-09-10 02:44 UTC, opendere commented on opendere/action.py
> +            self.previous_vote.target_user.nick if isinstance(self.previous_vote.target_user, opendere.game.User) else self.previous_vote.target_user,
`previous_target`, not `previous_vote`, per your last change.

Also, if you define `User.__str__(self): return self.nick`, you don't have to worry about the isinstance here. You can just do 

`f'{self.user.nick} has changed their vote from {self.previous_target} to {self.target_user}'`

2019-09-10 02:47 UTC, opendere commented on opendere/action.py
> +            self.messages = [(self.user.uid, f"you're changed from guarding {previous_target.nick} to guarding {target_user.nick} instead <3")]
I think we should write a generic helper function for all the classes here:

```
        if previous_target == "undecided":
            self.messages = [(self.user.uid, f"you're changed from {self.action_verb} {previous_target} to {self.action_verb} {target_user} instead <3")]
        else:
            self.messages = [(self.user.uid, f"you're {action_verb} {target_user.nick} from the scary yanderes <3")]

```

2019-09-11 13:01 UTC, libbies commented on opendere/ability.py
> +        previous_action = next((act for act in game.phase_actions if isinstance(act, type(self)) and user == act.user), None)
does this change how I would retrieve the previous_action?

2019-09-12 05:17 UTC, opendere requested changes

2019-09-12 05:17 UTC, opendere commented on opendere/ability.py
>          self.phases = phases
I think we should do `phases or []` so if phases is None it is an empty list

2019-09-12 05:17 UTC, opendere commented on opendere/ability.py
> +        previous_action = next((act for act in game.phase_actions if isinstance(act, self.action) and user == act.user), None)
I would isolate this to a separate function

2019-09-12 05:17 UTC, opendere commented on opendere/ability.py
> +            if self.command_public:
I recommend `recipient = game.channel if self.command_public else user.uid` so you don't repeat the same line twice.

2019-09-12 05:17 UTC, opendere commented on opendere/ability.py
> +            action_obj = self.action(game, user, target_user, ability=self, previous_action=previous_action)
Can the action be invalid? For example an invalid target? If so, `self.action()` should raise an Exception, and that exception should be handled. If there is an exception, it shouldn't remove the previous action.

2019-09-12 05:17 UTC, opendere commented on opendere/ability.py
> +        self.reveal_as = reveal_as
Note: we need to write a test case for this. Either you or I can do it

2019-09-12 05:17 UTC, opendere commented on opendere/ability.py
> +    requires_target = None
I recommend defaulting `requires_target = True` so you don't have to repeat it in all the classes

2019-09-12 05:17 UTC, opendere commented on opendere/action.py
> +        if self.target_user.is_protected and not isinstance(self, UnstoppableKillAction):
I recommend two separate implementations of apply rather than checking `isinstance`

2019-09-12 05:17 UTC, opendere commented on opendere/action.py
> +        for action in (act for act in self.actions_of_my_type if act.target_user):
I recommend `for vote_kill_action in self.actions_of_my_type`. It's fine if `target_user = None`, that just means no one is killed.

2019-09-12 05:17 UTC, opendere commented on opendere/action.py
> +        vote_counts = sorted(vote_counts.items(), key=lambda x: x[1], reverse=True)
probably not necessary to convert to list of lists. You can just

```
most_voted_user = max(vote_counts, key=vote_counts.get)
# if tie
if len([c for c in vote_counts.values() if c == vote_counts[most_voted_user]]) > 1:
    killed_user = None  # by default a tie results in no kill
    if self.game.phase_name == 'night':
        # however, at night, with ties, the first yandere to vote for someone other than abstain decides
        killed_user = next((...
````

2019-09-12 05:17 UTC, opendere commented on opendere/action.py
> +        if isinstance(most_voted_user, User) and not most_voted_user.is_protected:
should we make a generic `try_to_kill` function to handle this logic?

2019-09-12 05:17 UTC, opendere commented on opendere/action.py
> +                    self.game.completed_actions.append(kill)
I wonder if there's a cleaner way to do this that doesn't require `completed_actions`. Hmm, it's not obvious to me anyways.

2019-09-12 05:17 UTC, opendere commented on opendere/action.py
> +                    self.game.completed_actions.append(kill)
Seems like it's approximately the same thing, but since we have some actions that are never applied, we could have `self.game.phase_actions = OrderedDict[action, needs_application]`. Then iterate over phase_actions which still need to be applied. You can add `kill: False` to the OrderedDict.

2019-09-12 05:17 UTC, opendere commented on opendere/action.py
> +        if self.target_user.alignment:
`target_user.alignment` should always exist. Same with `target_user.role.appear_as`.

2019-09-12 05:17 UTC, opendere commented on opendere/action.py
> +        if self.target_user.appear_as:
I think we should remove this conditional too

2019-09-12 05:17 UTC, opendere commented on opendere/action.py
> +        if self.target_user.appear_as:
To accomplish this, we probably need the following in `Role.__init__`:

`self.appear_as = random.choice(self.appearances) if self.appearances else self.name`

2019-09-12 05:17 UTC, opendere commented on opendere/action.py
> +                f"you've been upgraded! you can reveal yourself to be a {self.target_user.role}"
not all `add_abilities` are reveals. 

Check `[new_ability.description for new_ability in self.target_user.role.upgrade_to.add_abilities]`

(as an aside, my name "add_abilities" is a bad name, maybe `new_abilities` is better)

2019-09-12 05:17 UTC, opendere commented on opendere/common.py
> +    def is_protected(self):
I don't think this should be a property of `User`. We should have isolation of concerns. `User` shouldn't know too much about things like `HideAction`. Maybe you know a better place for this, but what I was thinking was `staticmethod KillAction.is_protected(game, user)`

2019-09-19 15:12 UTC, opendere commented on opendere/action.py
> +        if self.game.is_protected(self.target_user) and not isinstance(self, UnstoppableKillAction):
nit: I recommend defining `is_protected` within action.py unless there is a reason `is_protected` is specific to the game.

2019-09-19 15:15 UTC, opendere commented on opendere/game.py
> +            if isinstance(act, HideAction) and act.user == user:
Would be cleaner to refactor this as `if act.protects_user(user)` so game.py doesn't need to know about the types of actions. Not necessary for this PR though.

2019-09-19 15:18 UTC, opendere commented on opendere/action.py
> +    def is_protected(game, user):
Maybe once you get rid of completed_actions, this should be a function of (phase_actions, user)

2024-12-10 15:52 UTC, closed without merging